# File: problem-statement-3/Dockerfile

# Use a lightweight Nginx (web server) image
FROM nginx:alpine

# Create a simple webpage inside the image
RUN echo '<h1>Success! The Docker image is running.</h1>' > /usr/share/nginx/html/index.html

# The server will run on port 80
EXPOSE 80
